services:
  gotify:
    image: gotify/server
    user: "1000:1000"
    ports:
      - 8080:80
    volumes:
      - gotify-data:/app/data

volumes:
  gotify-data:
    driver: local
    driver_opts:
      type: none
      device: /docker-vol/gotify
      o: bind
