services:
  stathub-server:
    image: hub.aiursoft.cn/aiursoft/stathub
    container_name: stathub_server
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
