services:
  nc-web:
    image: docker.aimersoft.org/nextcloud:stable
    networks: 
      - nextcloud
    depends_on:
      - nc-db
      - nc-redis
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - nextcloud-config:/var/www/html/config
      - nextcloud-custom-apps:/var/www/html/custom_apps
      - nextcloud-data:/mnt/data
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nc-db
      - REDIS_HOST=nc-redis
      - NEXTCLOUD_DATA_DIR=/mnt/data
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=1G
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=1024
    deploy:
      resources:
        limits:
          memory: 16384M

  nc-cron:
    image: docker.aimersoft.org/alpine
    networks: 
      - nextcloud
    depends_on:
      - nc-web
    entrypoint: ["/bin/sh", "-c", "apk add curl && sleep 20 && while true; do sleep 300; curl -s http://nc-web/cron.php; done"]
    deploy:
      resources:
        limits:
          memory: 128M

  nc-db:
    image: docker.aimersoft.org/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      - nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_dbpassword
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:
      resources:
        limits:
          memory: 8192M

  nc-redis:
    image: docker.aimersoft.org/redis:alpine
    volumes:
      - nextcloud-redis:/data
    networks: 
      - nextcloud
    deploy:
      resources:
        limits:
          memory: 8192M

networks:
  nextcloud:
    external: false

volumes:
  nextcloud-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-vol/nextcloud/db
  nextcloud-redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-vol/nextcloud/redis
  nextcloud-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-vol/nextcloud/config
  nextcloud-custom-apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-vol/nextcloud/custom_apps
  nextcloud-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker-vol/nextcloud/data
