services:
  gitlab:
    image: gitlab/gitlab-ee
    ports:
      - target: 2202
        published: 2202
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-config:/etc/gitlab
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648 # 2GB
    tmpfs:
      - /tmp:size=2G
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2202
        gitlab_sshd['enable'] = true
        gitlab_sshd['listen_address'] = '[::]:2202'
        gitlab_rails['gitlab_default_theme'] = 2
        letsencrypt['enabled'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        nginx['proxy_protocol'] = false
        nginx['http2_enabled'] = true
        prometheus_monitoring['enable'] = false
        sidekiq['metrics_enabled'] = false
        puma['exporter_enabled'] = false
    deploy:
      resources:
        limits:
          memory: 22G

volumes:
  gitlab-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/gitlab/data
  gitlab-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/gitlab/log
  gitlab-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/gitlab/config
