services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    networks:
      - ollama-docker

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - '/ollama/api=http://ollama:11434/api'
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false

